---
title: "L9KKE8_analysis"
author: "Kilicali Isildayancan"
date: "2023-04-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# L9KKE8

## First Domain

Sequence [1-330]: MNYPLTLDMDFMNNLDDLDDLYKELANYNDSTETPLVEYHLCSTVEGALLTSFKAVFMPVAYSLIFFLGMLGNILVLVILERHRQTRSSTETFLFHLAVADLLLVFILPFAVAQGPLGWVLGTFLCKIVIALHKINFYCSSLLLACIAVDRYLAIVHAVHAYRHRRLLSIHITCATIWLAGFLFALPEILFAKVSQPHLNDSLPRCTFSQENEAETKALLASRFLYHIGGFLLPMLVMGWCYVGVVHRLCQAQRRPQRQKAVRVAILVTSIFFLCWLPYHIVIFLDTLARLKAVGNTCELNGYLPAAITVCEFLGLAHCCLNPMLYTFAG


### Homologies

Psi-blast search against Swiss-Prot:


### Structure

### Motifs

### Conservation

Conservation of the protein from SwissProt with highest homology to the first domain

## Second domain

Sequence [352-685]: STVEGALLTSFKAVFMPVAYSLIFFLGMLGNILVLVILERHRQTRSSTETFLFHLAVADLLLVFILPFAVAQGPLGWVLGTFLCKIVIALHKINFYCSSLLLACIAVDRYLAIVHAVHAYRHRRLLSIHITCATIWLAGFLFALPEILFAKVSQPHLNDSLPRCTFSQENEAETKALLASRFLYHIGGFLLPMLVMGWCYVGVVHRLCQAQRRPQRQKAVRVAILVTSIFFLCWLPYHIVIFLDTLARLKAVGNTCELNGYLPAAITVCEFLGLAHCCLNPMLYTFAGVKFRSDLSRLLTKLGCAGPASLCQLFPSWRKSSLSESENATSLTTF 

### Homologies

Psi-blast search against Swiss-Prot:



### Structure

### Motifs

### Conservation

Conservation of the protein from SwissProt with highest homology to the second domain


## Relative domains

### Pairwise alignment


## Genomic sequence


