---
title: "L9JWP3 Analysis"
author: "Kilicali Isildayancan"
date: "2023-04-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# L9KKE8

## First Domain

Sequence [1-348]: MHGWPLTCTPEKRSPGQWLLAPKQHRTGKPTKSVLVVALLVIFQVCLCQDEVTDDYTGENTTVDYTIFETVCFKQDVRNFKAWFLPVMYSIICFIGLMGNGLVVLTYVYFKRLKTMTDTYLLNLAMADILFLLTLPFWAYSAAKSWIFGVHFCKLIFGIYKMSFFSGMLLLLCISIDRYVAIVQAVSAHRHRARVLLISKLSCVGIWMLAMMLSIPELLYSGTQRSSNEQALRCSLITERVEALITIQVAQMVIGFLVPLLAMSFCYLVIIRTLLQARNFERNKAIKVIIAVVVVFIVFQLPYNGVVLAQTVSNSTCELSKQLNIAYDVTYSLACVRCCINPFLYAFI


### Homologies

Psi-blast search against Swiss-Prot:


### Structure

### Motifs

### Conservation

## Second domain

Sequence [381-702]: QDVRNFKAWFLPVMYSIICFIGLMGNGLVVLTYVYFKRLKTMTDTYLLNLAMADILFLLTLPFWAYSAAKSWIFGVHFCKLIFGIYKMSFFSGMLLLLCISIDRYVAIVQAVSAHRHRARVLLISKLSCVGIWMLAMMLSIPELLYSGTQRSSNEQALRCSLITERVEALITIQVAQMVIGFLVPLLAMSFCYLVIIRTLLQARNFERNKAIKVIIAVVVVFIVFQLPYNGVVLAQTVSNSTCELSKQLNIAYDVTYSLACVRCCINPFLYAFIGVKFRNDLFKLFKDLGCLSQERLRQWSSCRHTGRSSMSVEAETTTTFSP

### Homologies

Psi-blast search against Swiss-Prot:



### Structure

### Motifs

### Conservation

## Relative domains

### Pairwise alignment


## Genomic sequence


